install:
  # g++
  - set PATH=%PATH%;C:\MinGW\bin
  # qmake
  - set QTDIR=C:\Qt\5.5\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin

build_script:
  - qmake
  - mingw32-make
  - cd release
  - appveyor_qmake_gcc_cpp14_boost.exe
